### ISSUE TITLE
v2 Release

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/eslint-config#19]
This issue tracks the progress of the v2 release.

Tasks:

- [x] Explicitly set all of the core ESLint rules (#1)
- [x] Add rules from eslint-plugin-import to base config (#8)
- [x] Inline TypeScript config extends (#12)
- [x] Add CHANGELOG (#18)
- [x] Update README with publishing instructions

**Comment by whymarrh** [comment]
> A new version of the package `@metamask/eslint-config` (2.0.0) was published at 2020-02-21T13:34:14.491Z from [redacted]. The shasum of this package was `4abeccbaafecd2e55be4dc97308e732e2eaa6799`.
