### ISSUE TITLE
v4 Release

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/eslint-config#67]
This issue tracks the progress of the v4 release.

Changes:

- [x] Update to ESLint 7 (#46)
- [x] Disable `space-before-function-paren` (#39)
- [x] Further restrict unused expressions (#66)

The draft version bump: https://github.com/MetaMask/eslint-config/pull/64

**Comment by whymarrh** [comment]
cc @MetaMask/devs is there anything else we want to put into this release?

**Comment by brad-decker** [comment]
@whymarrh I think that this one isn't too controversial, referencing from https://github.com/MetaMask/metamask-extension/pull/8595/

```
    // 'lines-around-comment': 'error',
    // Our eslint config has the default setting for this as error. This
    // include beforeBlockComment: true, but in order to match the prettier
    // spec you have to enable before and after blocks, objects and arrays
    // https://github.com/prettier/eslint-config-prettier#lines-around-comment
    'lines-around-comment': [
      'error',
      {
        beforeBlockComment: true,
        afterLineComment: false,
        allowBlockStart: true,
        allowBlockEnd: true,
        allowObjectStart: true,
        allowObjectEnd: true,
        allowArrayStart: true,
        allowArrayEnd: true,
      },
    ],
```

It mostly conforms to what we currently have set but with some additional allowances for comments at the start and end of certain object types. This moves us towards an eslint configuration that doesn't conflict with prettier.

**Comment by Gudahtt** [comment]
This has been released: https://github.com/MetaMask/eslint-config/releases/tag/v4.0.0
